### ISSUE TITLE
absinthe 1.5 support

### ISSUE THREAD

**Issue by moperacz** [rschef/rajska#23]
absinthe 1.5 changed schema pipeline and now it executes at compile time making use of rajska impossible

**Comment by gabrielpra1** [comment]
Tried to start working on it, but there seems to be a few issues with Absinthe 1.5 still. For example:

* `meta` no longer works for fields: https://github.com/absinthe-graphql/absinthe/issues/927
* functions in `meta` are not working: https://github.com/absinthe-graphql/absinthe/issues/928

**Comment by gabrielpra1** [comment]
Hey @moperacz, good news! With https://github.com/jungsoft/rajska/pull/30 and the release of Absinthe 1.5.4, this library is now compatible with the newest absinthe version 😄 

Please let me know if you encounter any issues when upgrading, cheers!
